### ISSUE TITLE
404 - PAGE NOT FOUND

### ISSUE THREAD

**Issue by malayli** [TinyCircuits/TinyCircuits-TinyShield-Nordic_nRF8001_BLE-ASD2113#1]
Hello,

This link returns a 404 error:

https://tiny-circuits.com/tiny-shield-nrf8001-bluetooth-low-energy.html

Best Regards,

Malik ALAYLI

**Comment by TinyCircuits** [comment]
Thanks for noticing this, the link is fixed now.

**Comment by malayli** [comment]
Ok I close the issue :)
